name: Auto Visit Streamlit

on:
  schedule:
    # 每3小时触发一次，脚本内部随机延时 1~30 分钟
    - cron: "0 */3 * * *"
  workflow_dispatch:  # 可手动触发

jobs:
  auto-visit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer auto visit
        env:
          GITHUB_USER: ${{ secrets.MY_GITHUB_USER }}
          GITHUB_PASS: ${{ secrets.MY_GITHUB_PAT }}
        run: node auto_visit.js
